# Zapret Configuration
# >.<

config=" --filter-udp=443 --hostlist=$MODPATH/lists/list-general.txt --hostlist=$MODPATH/lists/list-general-user.txt --hostlist-exclude=$MODPATH/lists/list-exclude.txt --hostlist-exclude=$MODPATH/lists/list-exclude-user.txt --ipset-exclude=$MODPATH/lists/ipset-exclude.txt --ipset-exclude=$MODPATH/lists/ipset-exclude-user.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=$MODPATH/fake/quic_initial_www_google_com.bin --new"
config="$config --filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=6 --new"
config="$config --filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake,hostfakesplit --dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com --dpi-desync-hostfakesplit-mod=host=www.google.com,altorder=1 --dpi-desync-fooling=ts --new"
config="$config --filter-tcp=443 --hostlist=$MODPATH/lists/list-google.txt --ip-id=zero --dpi-desync=fake,hostfakesplit --dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com --dpi-desync-hostfakesplit-mod=host=www.google.com,altorder=1 --dpi-desync-fooling=ts --new"
config="$config --filter-tcp=80,443 --hostlist=$MODPATH/lists/list-general.txt --hostlist=$MODPATH/lists/list-general-user.txt --hostlist-exclude=$MODPATH/lists/list-exclude.txt --hostlist-exclude=$MODPATH/lists/list-exclude-user.txt --ipset-exclude=$MODPATH/lists/ipset-exclude.txt --ipset-exclude=$MODPATH/lists/ipset-exclude-user.txt --dpi-desync=fake,hostfakesplit --dpi-desync-fake-tls-mod=rnd,dupsid,sni=ya.ru --dpi-desync-hostfakesplit-mod=host=ya.ru,altorder=1 --dpi-desync-fooling=ts --dpi-desync-fake-http=$MODPATH/fake/tls_clienthello_max_ru.bin --new"
config="$config --filter-udp=443 --ipset=$MODPATH/lists/ipset-all.txt --hostlist-exclude=$MODPATH/lists/list-exclude.txt --hostlist-exclude=$MODPATH/lists/list-exclude-user.txt --ipset-exclude=$MODPATH/lists/ipset-exclude.txt --ipset-exclude=$MODPATH/lists/ipset-exclude-user.txt --dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-fake-quic=$MODPATH/fake/quic_initial_www_google_com.bin --new"
config="$config --filter-tcp=80,443,8443 --ipset=$MODPATH/lists/ipset-all.txt --hostlist-exclude=$MODPATH/lists/list-exclude.txt --hostlist-exclude=$MODPATH/lists/list-exclude-user.txt --ipset-exclude=$MODPATH/lists/ipset-exclude.txt --ipset-exclude=$MODPATH/lists/ipset-exclude-user.txt --dpi-desync=fake,hostfakesplit --dpi-desync-fake-tls-mod=rnd,dupsid,sni=ya.ru --dpi-desync-hostfakesplit-mod=host=ya.ru,altorder=1 --dpi-desync-fooling=ts --dpi-desync-fake-http=$MODPATH/fake/tls_clienthello_max_ru.bin"
